options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"

substitutions:
  _REGION: europe-west2
  _AR_REPO: innerpeace
  _SERVICE: meeting-broker
  _RUNTIME_SA: bookings-bot@level-array-470911-t3.iam.gserviceaccount.com
  _SERVICE_ACCOUNT_EMAIL: bookings-bot@level-array-470911-t3.iam.gserviceaccount.com
  _IMPERSONATE_USER: thomaspal@innerpeace-developer.co.uk
  _CALENDAR_ID: thomaspal@innerpeace-developer.co.uk

steps:
  # Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail


        gcloud run deploy "${_SERVICE}" \
          --image="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA" \
          --region="${_REGION}" \
          --platform=managed \
          --service-account="${_RUNTIME_SA}" \
          --set-env-vars=NODE_ENV=production \
          --set-env-vars=SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL} \
          --set-env-vars=IMPERSONATE_USER=${_IMPERSONATE_USER} \
          --set-env-vars=CALENDAR_ID=${_CALENDAR_ID} \
          --allow-unauthenticated \
          --timeout=2000\
          --quiet

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
