options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"

substitutions:
  _REGION: europe-west2
  _SERVICE: meeting-broker
  # Set to your Cloud Run runtime service account (must exist)
  _RUNTIME_SA: bookings-bot@level-array-470911-t3.iam.gserviceaccount.com
  # Calendar config (works without keys if you SHARE a calendar to the service account)
  _CALENDAR_ID: primary
  _AUTH_MODE: workload

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: "Deploy from source (Buildpacks)"
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--source",".",
        "--region","${_REGION}",
        "--platform","managed",
        "--service-account","${_RUNTIME_SA}",
        "--allow-unauthenticated",
        "--port","8080",
        "--timeout","1200",
        "--set-env-vars","NODE_ENV=production,AUTH_MODE=${_AUTH_MODE},CALENDAR_ID=${_CALENDAR_ID}",
        "--quiet"
      ]

