options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"

substitutions:
  _REGION: "europe-west2"
  _AR_REPO: "innerpeace" # name of your Artifact Registry repo
  _SERVICE: "meeting-broker"
  _RUNTIME_SA: "bookings-bot@level-array-470911-t3.iam.gserviceaccount.com"

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - -f
      - Dockerfile
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud run deploy "${_SERVICE}" \
          --image="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA" \
          --region="${_REGION}" \
          --platform=managed \
          --allow-unauthenticated \
          --service-account="${_RUNTIME_SA}" \
          --quiet

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
