substitutions:
  _REGION: europe-west2
  _REPO: innerpeace
  _SERVICE: meeting-broker
  _IMAGE: ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}

steps:
  # Build container from the server/ subdir
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}:$SHORT_SHA", "server"]

  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_IMAGE}:$SHORT_SHA"]

  # Deploy to Cloud Run (set envs here or do it once in the console)
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--region","${_REGION}",
        "--image","${_IMAGE}:$SHORT_SHA",
        "--allow-unauthenticated",
        # Set your env vars (safe because no secrets/keys here)
        "--set-env-vars","CALENDAR_ID=REPLACE_WITH_CALENDAR_ID",
        "--set-env-vars","USE_MEET=auto",
        # These two matter for your Calendar client:
        "--set-env-vars","GOOGLE_SERVICE_ACCOUNT_EMAIL=REPLACE_SA_EMAIL",
        "--set-env-vars","GOOGLE_DELEGATED_USER=REPLACE_USER_EMAIL"
      ]

images:
  - "${_IMAGE}:$SHORT_SHA"
