options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"

# Define BOTH your own substitutions and the IMAGE one the old trigger keeps expecting.
substitutions:
  _REGION: "europe-west2"
  _AR_REPO: "innerpeace"                         # your Artifact Registry repo
  _SERVICE: "meeting-broker"                     # Cloud Run service name
  _RUNTIME_SA: "bookings-bot@level-array-470911-t3.iam.gserviceaccount.com"
  IMAGE: "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA"

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${IMAGE}
      - -f
      - Dockerfile
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${IMAGE}

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        gcloud run deploy "${_SERVICE}" \
          --image="${IMAGE}" \
          --region="${_REGION}" \
          --platform=managed \
          --allow-unauthenticated \
          --service-account="${_RUNTIME_SA}" \
          --quiet

images:
  - ${IMAGE}
