# cloudbuild.yaml
# Build → Push → Deploy to Cloud Run (Artifact Registry)
# Works whether your Dockerfile is at repo root or in a subfolder.

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1200s"

# ── Set these for your project ────────────────────────────────────────────────
substitutions:
  _REGION: "europe-west2"                                   # Artifact Registry & Cloud Run region
  _AR_REPO: "innerpeace"                                    # Artifact Registry repo name
  _SERVICE: "meeting-broker"                                # Cloud Run service name
  _RUNTIME_SA: "bookings-bot@level-array-470911-t3.iam.gserviceaccount.com"

  # Tell Cloud Build where your Dockerfile is:
  # If Dockerfile is in the repo root:
  _DOCKERFILE: "Dockerfile"
  _DOCKER_CONTEXT: "."

  # If your Dockerfile is in a folder (e.g. server/), override in UI or edit:
  # _DOCKERFILE: "server/Dockerfile"
  # _DOCKER_CONTEXT: "server"
# ──────────────────────────────────────────────────────────────────────────────

steps:
  # (Optional) quick listing so you can see what Cloud Build sees
  - name: alpine
    entrypoint: sh
    args: ["-lc", "pwd; ls -la; echo '---'; ls -la ${_DOCKER_CONTEXT} || true"]

  # Build the image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - -f
      - ${_DOCKERFILE}
      - ${_DOCKER_CONTEXT}

  # Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        set -euo pipefail
        IMAGE="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA"
        gcloud run deploy "${_SERVICE}" \
          --image="${IMAGE}" \
          --region="${_REGION}" \
          --platform=managed \
          --allow-unauthenticated \
          --service-account="${_RUNTIME_SA}" \
          --quiet

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
